[tool.poetry]
name = "tg-bot-api"
version = "0.1.0"
description = ""
authors = ["Grigoruk <grimax14@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
mypy = "^1.5.1"
ruff = "^0.0.289"
deptry = "^0.12.0"


[tool.poetry.group.dev.dependencies]
sqlalchemy = "^2.0.20"
pydantic = "^2.3.0"
fastapi = "^0.103.1"
uvicorn = "^0.23.2"
asyncpg = "^0.28.0"
pydantic-settings = "^2.0.3"


[tool.poetry.group.deploy.dependencies]
alembic = "^1.12.0"

[tool.ruff]
target-version = "py311"
line-length = 120
select = ["ALL"]
ignore = [
    "D104", # pydocstyle - missing docstring in public package
]
src = ["src", "tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
